services:
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        image: georgionrails/fastapi:latest
        container_name: fastapi-container
        ports:
            - "8000:8000"
        networks:
            - app_network
        restart: always
        environment:
            - ENVIRONMENT=production
        command: uvicorn main:app --host 0.0.0.0 --port 8000
    nginx:
        image: nginx:latest
        container_name: nginx-proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - fastapi
        networks:
            - app_network
    
networks:
    app_network:
      driver: bridge