version: "3.8"

services:
    fastapi:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi-app
        image: georgionrails/fastapi-app:latest
        ports:
            - "8000:8000"

        volumes:
            - .:/app
        environment:
            - ENVIRONMENT=production
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        


    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - fastapi