name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/fastapi:latest ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi:${{ github.sha }}

      - name: Debug SSH Connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo -e "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ls -la private_key.pem
          ssh-keygen -yf private_key.pem || echo "Invalid key file!"

      - name: Test SSH Login
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no georgia_u_nwa@34.69.88.137 "echo 'SSH connection successful'"

      - name: Set up SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo -e "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        
      - name: Install Docker & Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem georgia_u_nwa@34.69.88.137 << 'EOF'
            echo "📦 Installing Docker & Docker Compose..."
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose
            sudo usermod -aG docker $(whoami)
            sudo systemctl enable --now docker
          EOF
        
      - name: Deploy on Google Cloud
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo -e "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no georgia_u_nwa@34.69.88.137 << EOF
            
            echo "📦 Ensuring Docker & Docker Compose are installed..."
            if ! command -v docker &> /dev/null; then
              echo "🚨 Docker is not installed. Installing..."
              sudo apt-get update && sudo apt-get install -y docker.io
            fi
            if ! command -v docker-compose &> /dev/null; then
              echo "🚨 Docker Compose is not installed. Installing..."
              sudo apt-get install -y docker-compose
            fi
            
            echo "🔄 Pulling latest Docker image..."
            docker pull georgionrails/fastapi:latest

            echo "🛑 Stopping old containers..."
            cd /home/georgia_u_nwa/fastapi-book-project
            docker-compose down

            echo "🧹 Cleaning up unused Docker images..."
            docker system prune -af

            echo "🚀 Starting new containers..."
            docker-compose up -d --build

            echo "✅ Deployment successful!"
          EOF
      - name: Clean Up
        run: rm -f private_key.pem
      
        