name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build, tag, and push docker image
        run: |
          docker build -t fastapi-app:latest .
          docker tag fastapi-app "${{ secrets.DOCKER_USERNAME }}/fastapi-app"
          docker push "${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest"

      - name: Install docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Deploy with docker-compose
        run: |
          docker pull "${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest"
          docker-compose down
          docker-compose up -d
        